---
title: "projet ANAd"
author: 'Mame Diarra Toure-imane ALLA: binome 20'
date: "12/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(reshape2)
library(LaplacesDemon)
```

```{r}
set.seed(3)
K<-3
p<-50
n<-200
pi<-c(1/3,1/3,1/3)
M<-matrix(runif(K*p),K,p)
M[K,]<-1-M[1,]
nks<-rmultinom(1,200,prob = pi)
Z<-rep(1:length(nks),nks)
X <-do.call(rbind, 
                  mapply(function(nk,k){
                    matrix(rbernoulli(nk*p,p=M[k,]),
                           nrow = nk,
                           ncol=p,
                           byrow = TRUE)}, nks,1:K))

kmeans(X,3,nstart = 10)->res.kmeans
tidyData<-melt(X[order(res.kmeans$cluster),order(M[1,])])

ggplot(tidyData, aes(x = Var2, y = Var1)) + 
  geom_raster(aes(fill=value)) + 
  scale_fill_brewer(aesthetics = "fill") + 
  labs(x="Variables", y="Individus", title="Matrix") 
```
#exercice 3
```{r}
Init.EM <- function(x,k){
  proportions <- rep(1/k,k)#initialisation des proportions
  eps <- 0.1
  n <- nrow(x)
  p <- ncol(x)
  A <- x[sample(1:nrow(x),k),]
  mu <- matrix(233,k,p)
  for(l in 1:k){
    for( i in 1:p){
      if(A[l,i]==0){
      mu[l,i] <- eps
      }
      else{
        mu[l,i] <- (1-eps)
      
      }
      
    }
      }
  #initialisation des vecteurs de proba
  mu[k,]<-1-M[1,]
  parameters=list(proportions=proportions,mu=mu)
  return(parameters)
}
Init.EM(X,3)
```

```{r}
E.EM <- function(x,parameters){
  K<-nrow(parameters$mu)
  n <- nrow(x)
  p <- ncol(x)
  tik <- matrix(0,nrow=nrow(x),ncol=K)
      for (k in 1:K){
        pik <- parameters$proportions[k]
        muk <- parameters$mu[k]
         for(i in 1:n){
           tik[i,k] <- 1
           for (j in 1:p){
          tik[i,k]=tik[i,k]*(muk[j]**(x[i,j]))*((1-muk[j])**(1-x[i,j]))
           }
           }
    tik[,k] <- pik*tik[,k]
      }
  tik <- tik/rowSums(tik)
  return(tik)
}
parameters <- Init.EM(X,3)
E.EM(X,parameters)

```
```{r}
Zik <- matrix(0,nrow=200,ncol=3)
for( i in 1:200){
  for(k in 1:3){
    if(Z[i]==k)
    Zik[i,k]=1
  }
} 
mean(Zik)
mean(tik)
```
```{r}
M.EM <- function(parameters,tik,x){
  K<-ncol(tik)
  n=200
  muk<-matrix(0,ncol(tik),50)
 
  for(k in 1:K){
    a=rep(0,50)
    for (i in 1:200){
      a=a+(tik[i,k]*x[i,])
    }
    muk[k,] <- (1/sum(tik[,k]))*a
  }
pik <- colSums((tik))/n
parameters <-list(proportions=pik,muk=muk)
return(parameters)
}
M1 <- M.EM(Init.EM(X,K),E.EM(X,Init.EM(X,K)),X)
M1
```

```{r}
EM <-  function(x,k){
  parameters=Init.EM(x,k)
  tik=E.EM(x,parameters)
  parameters.new <- M.EM(parameters,tik,x)
  iter=0
  parameters.new$mu
  while(sum(abs(unlist(parameters.new)-unlist(parameters)))>(1e-10)){
    tik=E.EM(x,parameters.new)
    parameters <- parameters.new
    parameters.new <- M.EM(parameters,tik,x)
    #print(parameters.new)
    #print(parameters)
    #print((sum(abs(unlist(parameters.new)-unlist(parameters)))>(1e-20)))
    iter<-iter+1
    #print(iter)
  }
  iter
  return(c(parameters.new,iter))
}
EM(X,3)
```